const leguajes_p = new Set()
leguajes_p.add("java")
leguajes_p.add("C++")
leguajes_p.add("python")
leguajes_p.add("C++")
leguajes_p.add("C#")
leguajes_p.add("javascript")
leguajes_p.add("java")
console.log(leguajes_p)
